WebPort: ""
devicetype: ""
Device: []
Redis:
    Addr: ""
    Password: ""
    Id_rsa: ""
BUserCk: []
ChargeUid: []
LotteryUid: []
SpecialUid: []
WebUserAgent: ""
MobileUserAgent: ""
DDNS:
    Update: false
    ZoneID: ""
    DnsRecordId: ""
    ApiToken: ""
    Type: ""
    Name: ""
Server3: ""
BCoinExchange: ""
Ql:
    Addr: ""
    Port: ""
    ClientId: ""
    ClientSecret: ""
Model: ""
