WebPort: ""
devicetype: ""
RemoteDevice: []
LocalDevice:
    Host: false
    IP: ""
    RedisPort: ""
    QLPort: ""
    ProxyPort: ""
    Name: ""
    Ql:
        QLPort: ""
        ClientId: ""
        ClientSecret: ""
    DDNS:
        ZoneID: ""
        DnsRecordId: ""
        ApiToken: ""
        Type: ""
        Name: ""
    Tools:
        Daily: false
        CrawlerLottery: false
        DDNS: false
Redis:
    Addr: ""
    Password: ""
    Id_rsa: ""
BUserCk: []
ChargeUid: []
LotteryUid: []
SpecialUid: []
WebUserAgent: ""
MobileUserAgent: ""
Server3: ""
BCoinExchange: ""
Model: ""
