WebPort: 127.0.0.1:2025
devicetype: ""
RemoteDevice:
    - Host: true
      IP: 47.117.144.123
      RedisPort: "16379"
      ProxyPort: "0"
      Name: ali
      Ql:
        QLPort: "15700"
        ClientId: G_NnpUwLV8dq
        ClientSecret: y112y2WwJwsIFx_78L_ExtRs
      DDNS:
        ZoneID: ""
        DnsRecordId: ""
        ApiToken: ""
        Type: AAAA
        Name: like.151580.xyz
      Tools:
        Daily: true
        CrawlerLottery: true
        DDNS: true
    - Host: false
      IP: 115.120.234.147
      RedisPort: ""
      ProxyPort: ""
      Name: hw
      Ql:
        QLPort: "15700"
        ClientId: z8y_k4DOHVl5
        ClientSecret: XrCj-0ddMc3k7NgQhR6xdWM3
      DDNS:
        ZoneID: ""
        DnsRecordId: ""
        ApiToken: ""
        Type: ""
        Name: ""
      Tools:
        Daily: true
        CrawlerLottery: true
        DDNS: false
LocalDevice:
    Host: false
    IP: ""
    RedisPort: ""
    ProxyPort: "0"
    Name: LocalDevice
    Ql:
        QLPort: "15700"
        ClientId: W0JwCYL8r--F
        ClientSecret: Tggi3oYMT2j-9Uv47_ww9Nsj
    DDNS:
        ZoneID: ""
        DnsRecordId: ""
        ApiToken: ""
        Type: ""
        Name: ""
    Tools:
        Daily: true
        CrawlerLottery: true
        DDNS: false
Redis:
    Addr: ""
    Password: ""
    Id_rsa: ""
BUserCk: []
ChargeUid:
    - Name: ""
      Uid: "2149231"
LotteryUid:
    - Name: ""
      Uid: "2595733"
    - Name: ""
      Uid: "492426375"
    - Name: ""
      Uid: "100680137"
    - Name: ""
      Uid: "226257459"
    - Name: ""
      Uid: "5536630"
    - Name: ""
      Uid: "417545609"
    - Name: ""
      Uid: "373018905"
SpecialUid:
    - Name: ""
      Uid: "885439"
    - Name: ""
      Uid: "1673762431"
    - Name: ""
      Uid: "373018905"
    - Name: ""
      Uid: "99584491"
WebUserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
MobileUserAgent: Mozilla/5.0 (Linux; Android 12; 24031PN0DC Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Safari/537.36 Mobile os/android model/24031PN0DC build/8020300 osVer/12 sdkInt/32 network/2 BiliApp/8020300 mobi_app/android channel/yingyongbao Buvid/XU812D18534B34C4113916044792A64880198 sessionID/bde3aecb innerVer/8020300 c_locale/zh_CN s_locale/zh_CN disable_rcmd/0 8.2.0 os/android model/24031PN0DC mobi_app/android build/8020300 channel/yingyongbao innerVer/8020300 osVer/12 network/2
Server3: sctp3776tdvvefnyamdjc7g51zvprjn
BCoinExchange: "74199115"
Model: test
